#! /bin/csh -f
#############################################################################
#
# Script to compare working code version on RPi to configured version
#
#############################################################################
#
# Specify root where old version exists
#set ROOT="/media/${USER}/305f60b3-8413-4edb-afc1-4e4ce064aab3/home/${USER}"
#set ROOT="/media/${USER}/pi"
set ROOT="/media/${USER}/marconi"
#set ROOT="/media/${USER}/sproul"
set ROOT="/media/${USER}/calvin"
#set ROOT="/mnt/sproul"
#set ROOT="/mnt/calvin"
#set ROOT="/mnt/Luther"
#set ROOT="/media/${USER}/sproul-win"
#set ROOT="/media/${USER}/acer"
#set ROOT="/media/${USER}/cartman"
if( !(-e $ROOT) )then
    set ROOT="${ROOT}2"
endif

# Add path down to old version
set N=`echo $HOME | wc -c`
echo N=$N
#set PTH=`pwd | cut -c ${N}-`
set PTH=`pwd | sed 's/\/home2//g' | cut -c ${N}-`
echo PTH=$PTH
set old=${ROOT}${PTH}
echo OLD=$old

# Override if needed
#set old='save45'

rm -f DIFFS
foreach i (*.py *.bat *.txt *.md run_demos DIFF st99*)
    echo $i
    set n=`diff -w $old/$i $i | wc -l`
    if( !( -e $old/$i ) )then
        echo NO SUCH FILE $old/$i
        cp $i $old/$i
    else if( $n > 0 ) then
        echo ---------------------------------- >> DIFFS
        echo $i >> DIFFS
        echo " " >> DIFFS
        diff -w $old/$i $i >> DIFFS
        echo " " >> DIFFS
        
        kompare $i $old/$i
        #kompare $old/$i $i
    endif
end

chmod +x *.py run_demos DIFF

cat DIFFS
